# MySQL. Versions 5.5.8 and up are supported.
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: alantr
  password: Naruto101
  host: localhost

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: inventory_tracker_development

test:
  <<: *default
  database: inventory_tracker_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: inventory_tracker_production
  username: inventory_tracker
  password: <%= ENV["INVENTORY_TRACKER_DATABASE_PASSWORD"] %>
